# 1. Usar una imagen base con Python preinstalado
FROM python:3.9-slim

# 2. Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# 3. Copiar los archivos necesarios al contenedor
COPY requirements.txt requirements.txt
COPY app.py app.py
COPY model.pkl model.pkl

# 4. Instalar las dependencias especificadas
RUN pip install --no-cache-dir -r requirements.txt

# 5. Exponer el puerto 5000 para que la aplicación sea accesible
EXPOSE 5000

# 6. Especificar el comando para iniciar la aplicación
CMD ["python", "app.py"]
